export const SET_CATEGORY_EDITED = "SET_CATEGORY_EDITED";
export const GET_CATEGORIES_DATA = "GET_CATEGORIES_DATA";
export const GET_CATEGORIES_BY_GROUP_ID = "GET_CATEGORIES_BY_GROUP_ID";
export const GET_USER_CATEGORIES_DATA = "GET_USER_CATEGORIES_DATA";
