export const PROFILE_CONSTANTS = {
  TYPE_LIST: "list",
  TYPE_AVATAR: "avatar",
  TYPE_TEXT: "text",
  PANEL0: "panel0",
  PANEL1: "panel1",
  PANEL2: "panel2",
  PANEL3: "panel3",
  PANEL4: "panel4",
  PANEL5: "panel5",
  PANEL6: "panel6",
  CHANGE_AVATAR: "Change Avatar",
  USERNAME: "Username",
  GENDER: "Gender",
  BIRTH_DATE: "Date of Birth",
  FAVORITE_CATEGORIES: "Favorite Categories",
  MANAGE_NOTIFICATIONS: "Manage notifications",
  LINKED_ACCOUNTS: "Linked accounts",
  BIRTH_DATE_FORMAT: "D MMM YYYY",
  MIN_SIZE_OF_AVATAR: 4096,
  SMALL_IMAGE: "Image is too small",
  REQUIRED_IMAGE: "Image is required",
  SUBMIT: "Submit",
  CLEAR: "Clear",
  CHANGE_PASSWORD: "Change Password",
  PASSWORD_NOT_MATCH: "Password do not match",
  DATE_INCORRECT: "Date is incorrect",
  GENDERS: ["Male", "Female", "Other"],
  FIELDS: ["oldPassword", "newPassword", "repeatPassword"],
  FIELDS_LABEL: [
    "Input current password",
    "Input new password",
    "Repeat new password",
  ],
  OLDEST_DATE_OF_CHOICE: 115,
  YOUNGEST_DATE_OF_CHOICE: 14,
};

export const EMPTY_ACCORDION_CONTENT = 0;
export const SUBMIT = "Submit";
export const CLEAR = "Clear";
