const profileConstants = {
  TYPE_LIST: "list",
  TYPE_AVATAR: "avatar",
  TYPE_TEXT: "text",
  PANEL0: "panel0",
  PANEL1: "panel1",
  PANEL2: "panel2",
  PANEL3: "panel3",
  PANEL4: "panel4",
  PANEL5: "panel5",
  PANEL6: "panel6",
  CHANGE_AVATAR: "Change Avatar",
  USERNAME: "Username",
  GENDER: "Gender",
  BIRTH_DATE: "Date of Birth",
  FAVORITE_CATEGORIES: "Favorite Categories",
  MANAGE_NOTIFICATIONS: "Manage notifications",
  LINKED_ACCOUNTS: "Linked accounts",
  BIRTH_DATE_FORMAT: "D MMM YYYY",
  MIN_SIZE_OF_AVATAR: 4096,
  SMALL_IMAGE: "Image is too small",
  REQUIRED_IMAGE: "Image is required",
  SUBMIT: "Submit",
  CLEAR: "Clear",
  CHANGE_PASSWORD: "Change Password",
  fields: ["oldPassword", "newPassword", "repeatPassword"],
  fieldsLabel: [
    "Input current password",
    "Input new password",
    "Repeat new password",
  ],
};

export default profileConstants;
