export const GET_EVENTS_SCHEDULE_DATA = "GET_EVENTS_SCHEDULE_DATA";
export const RESET_EVENTS_SCHEDULE = "RESET_EVENTS_SCHEDULE";
export const GET_EVENT_SCHEDULE_DATA = "GET_EVENT_SCHEDULE_DATA";
export const RESET_EVENT_SCHEDULE = "RESET_EVENT_SCHEDULE";
