export const GET_TEMPLATES_SUCCESS = "GET_TEMPLATES_SUCCESS";
export const GET_TEMPLATE_SUCCESS = "GET_TEMPLATE_SUCCESS";
export const GET_TEMPLATE_PROPERTIES_SUCCESS =
  "GET_TEMPLATE_PROPERTIES_SUCCESS";
